
services:
  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailer
    restart: unless-stopped
    volumes:
      - ./docker/mailer/data:/data
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - api

###< symfony/mailer ###
