services:
  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - "9000:9000"
    depends_on:
      - redis
      - postgres
      - localstack
    networks:
      - api

  nginx:
    image: nginx:stable-alpine
    ports:
      - 127.0.0.1:${NGINX_PORT:-8080}:80
    volumes:
      - ./backend:/app:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro,cached
      - ./docker/nginx/logs:/var/log/nginx/
    depends_on:
      - php
    networks:
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_DB: ${POSTGRES_DB:-symfony}
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d symfony -h localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3,sqs,sns,rds
    volumes:
      - ./docker/localstack:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api

  react:
    build:
      context: ./
      dockerfile: ./docker/react/Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm run build && npm run dev"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - php
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - api

networks:
  api:
    driver: bridge
